root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false